plugins {
    id("io.micronaut.build.internal.redis-module")
}

dependencies {
    api project(":micronaut-redis-lettuce-core")
    api project(":micronaut-redis-lettuce-cache")
    api project(":micronaut-redis-lettuce-session")
}

micronautBuild {
    descriptor {
        parentModuleId = "io.micronaut.redis:micronaut-redis-lettuce"
    }
}
