=== Customizing The Redis Configuration

You can customize the Redis configuration using any properties exposed by the api:configuration.lettuce.DefaultRedisConfiguration[] class. For example, in the application configuration file:

.Customizing Redis Configuration
[configuration]
----
redis:
    uri: redis://localhost
    ssl: true
    timeout: 30s
----

=== Multiple Redis Connections

You can configure multiple Redis connections using the `redis.servers` setting. For example:

.Customizing Redis Configuration
[configuration]
----
redis:
    servers:
        foo:
            uri: redis://foo
        bar:
            uri: redis://bar
----

In which case the same beans will be created for each entry under `redis.servers` but exposed as `@Named` beans.

.Using StatefulRedisConnection
[source,groovy]
----
@Inject @Named("foo") StatefulRedisConnection<String, String> connection;
----

The above example will inject the connection named `foo`.

=== MasterReplica Configuration
You can configure a standalone redis instance with replicas by supplying the `redis.replica-uris` setting to list out the location of all replicas.

.MasterReplica Redis Configuration
[source,yaml]
----
redis:
    uri: redis://localhost
    replica-uris:
      - redis://localhost:6578
    ssl: true
    timeout: 30s
----

=== ReadFrom Settings
For MasterReplica and Cluster configurations the https://github.com/redis/lettuce/wiki/ReadFrom-Settings[ReadFrom Setting] can be configured using the `redis.read-from` setting.

.ReadFrom Redis Configuration
[source,yaml]
----
redis:
    uris:
      - redis://localhost
    read-from: replicaPreferred
----

This setting accepts a string matching the values accepted in the https://github.com/redis/lettuce/blob/main/src/main/java/io/lettuce/core/ReadFrom.java#L190[ReadFrom.valueOf] method. These are currently `master`, `masterPreferred`, `upstream`, `upstreamPreferred`, `replica`, `replicaPreferred`, `lowestLatency` , `any`, and `anyReplica`.

=== Named connection codec configuration

When using named redis connections, you can change the codec for each connection by supplying a named RedisCodec bean.
For example:

.Supply different codecs for named connections
[source,groovy]
----
include::{testsredis}/NamedCodecFactory.groovy[tags=namedCodec, indent=0]
include::{testsredis}/NamedCodecFactory.groovy[tags=namedCodec2, indent=0]
----

== Redis Health Checks

When the `redis-lettuce` module is activated a api:configuration.lettuce.health.RedisHealthIndicator[] is activated resulting in the `/health` endpoint and https://docs.micronaut.io/latest/api/io/micronaut/health/CurrentHealthStatus.html[CurrentHealthStatus] interface resolving the health of the Redis connection or connections.

The health indicator is enabled by default. To disable the health endpoint, you can do so via the config. 
```redis:
   health:
    enabled: false
```

See the section on the https://docs.micronaut.io/latest/guide/index.html#healthEndpoint[Health Endpoint] for more information.

== Disabling Redis

You can disable the creation of Redis connections using the `redis.enabled` setting, through configuration:

.Disabling Redis
[configuration]
----
redis:
    enabled: false
----
