pluginManagement {
    repositories {
        gradlePluginPortal()
        mavenCentral()
    }
}

plugins {
    id("io.micronaut.build.shared.settings") version "8.0.2"
}

rootProject.name = 'redis-parent'

include 'redis-bom'
include 'docs-examples:codecs-java'
include 'docs-examples:codecs-groovy'
include 'docs-examples:codecs-kotlin'
include 'docs-examples:pubsub-java'
include 'docs-examples:pubsub-groovy'
include 'docs-examples:pubsub-kotlin'
include 'redis-lettuce'
include 'redis-lettuce-core'
include 'redis-lettuce-cache'
include 'redis-lettuce-session'
include 'redis-lettuce-pubsub'
include 'test-suite-graal'
include 'test-suite-utils'

micronautBuild {
    useStandardizedProjectNames = true
    importMicronautCatalog()
    importMicronautCatalog("micronaut-cache")
    importMicronautCatalog("micronaut-micrometer")
    importMicronautCatalog("micronaut-serde")
    importMicronautCatalog("micronaut-session")
}
