plugins {
    id "io.micronaut.build.internal.redis-native-tests"
}

micronaut {
    version "5.1.5"
    testRuntime "junit5"
    enableNativeImage false
    processing {
        incremental(true)
        annotations("helloworld.*")
    }
}

configurations.all {
    resolutionStrategy.dependencySubstitution {
        substitute module('io.micronaut.redis:micronaut-redis-lettuce') using project(':micronaut-redis-lettuce')
    }
}

dependencies {
    implementation mn.micronaut.context
    implementation mn.micronaut.jackson.databind
    implementation platform(libs.micronaut.test)
    implementation project(':micronaut-redis-lettuce')
    testImplementation(project(':test-suite-utils'))
    implementation mn.snakeyaml
    runtimeOnly mnLogging.logback.classic
    testRuntimeOnly(libs.junit.platform.launcher)
    testImplementation(platform(mnTest.boms.testcontainers))
    testImplementation(libs.testcontainers)
}
