plugins {
    id("io.micronaut.build.internal.redis-module")
}

dependencies {
    annotationProcessor mn.micronaut.graal

    api libs.managed.lettuce

    compileOnly mn.micronaut.management
    compileOnly mnMicrometer.micronaut.micrometer.core

    testImplementation(platform(mnTest.boms.testcontainers))
    testImplementation(libs.testcontainers)
    testAnnotationProcessor mn.micronaut.inject.java

    testImplementation mn.reactor
    testImplementation project(":micronaut-redis-lettuce-cache")
    testImplementation mn.micronaut.inject.java
    testImplementation mn.micronaut.management
    testImplementation mnMicrometer.micronaut.micrometer.core
    testImplementation mnSerde.micronaut.serde.jackson
    testImplementation mn.micronaut.jackson.databind
    testImplementation mn.micronaut.function.web
    testImplementation mn.micronaut.http.client
    testImplementation mn.snakeyaml

    testRuntimeOnly mn.micronaut.http.server.netty
    testRuntimeOnly(libs.junit.platform.launcher)
    testRuntimeOnly(mnLogging.logback.classic)
}

micronautBuild {
    descriptor {
        parentModuleId = "io.micronaut.redis:micronaut-redis-lettuce"
    }
    binaryCompatibility.enabledAfter("7.0.0")
}
